### ISSUE TITLE
old carbon version

### ISSUE THREAD

**Issue by m7md3omr** [GeniusTS/laravel-hijri-dates#1]
I have been using hijiri-date  last year in php project and it works fine 
but now when trying laravel package it produce composer error due to old nesbot/carbon package version

update the carbon package version could solve the problem

**Comment by aboudeh87** [comment]
Can you write the error appears please

**Comment by m7md3omr** [comment]
OK, 
I am using 
Ubuntu Linux 18.04, 
laravel 5.8

  I have tried to install the package again to get the error message , but it works ,  and i have tried twice actually and it installed peacefuly :) ,
upgrading nesbot/carbon works fine , thanks brother.

thanks for the great package

**Comment by aboudeh87** [comment]
Great, you are welcome brother
